import numpy as np
from .types import PostProcessBatchParams as PostProcessBatchParams, PostProcessParams as PostProcessParams, PreProcessBatchParams as PreProcessBatchParams, PreProcessParams as PreProcessParams
from edgeiq.bounding_box import BoundingBox as BoundingBox

def trt_pre_process(params: PreProcessParams) -> np.ndarray: ...
def trt_ssd_pre_process(params: PreProcessParams) -> np.ndarray: ...
def trt_ssd_post_process(params: PostProcessParams): ...
def trt_yolo_pre_process(params: PreProcessParams) -> np.ndarray: ...
def trt_yolo_pre_process_batch(params: PreProcessBatchParams) -> np.ndarray: ...
def process_nms_boxes(detections: np.ndarray, overlap_threshold: float): ...
def trt_yolo_post_process(params: PostProcessParams): ...
def trt_yolo_post_process_batch(params: PostProcessBatchParams): ...
