
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-25T11:51:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fc120016a7880faa74859883466fade1d15ca08",
 "version": "2.5.2rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
