
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-26T16:19:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bf0173938a1e193728116385c39295204bd185d",
 "version": "2023.7.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
