# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    Sidra API version: 1.12.3.post2
    Contact: sidra@plainconcepts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PipelineTemplateFullDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'template': 'str',
        'default_value': 'str',
        'item_id': 'str',
        'parameters': 'str',
        'id_pipeline_type': 'PipelineTypeEnum',
        'id_pipeline_template_platform': 'PipelineTemplatePlatformEnum',
        'id_plugin_version': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'template': 'template',
        'default_value': 'defaultValue',
        'item_id': 'itemId',
        'parameters': 'parameters',
        'id_pipeline_type': 'idPipelineType',
        'id_pipeline_template_platform': 'idPipelineTemplatePlatform',
        'id_plugin_version': 'idPluginVersion'
    }

    def __init__(self, id=None, name=None, description=None, template=None, default_value=None, item_id=None, parameters=None, id_pipeline_type=None, id_pipeline_template_platform=None, id_plugin_version=None):  # noqa: E501
        """PipelineTemplateFullDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._template = None
        self._default_value = None
        self._item_id = None
        self._parameters = None
        self._id_pipeline_type = None
        self._id_pipeline_template_platform = None
        self._id_plugin_version = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if template is not None:
            self.template = template
        if default_value is not None:
            self.default_value = default_value
        if item_id is not None:
            self.item_id = item_id
        if parameters is not None:
            self.parameters = parameters
        if id_pipeline_type is not None:
            self.id_pipeline_type = id_pipeline_type
        if id_pipeline_template_platform is not None:
            self.id_pipeline_template_platform = id_pipeline_template_platform
        if id_plugin_version is not None:
            self.id_plugin_version = id_plugin_version

    @property
    def id(self):
        """Gets the id of this PipelineTemplateFullDto.  # noqa: E501

        Unique identifier of each PipelineTemplate. NotNull.  # noqa: E501

        :return: The id of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PipelineTemplateFullDto.

        Unique identifier of each PipelineTemplate. NotNull.  # noqa: E501

        :param id: The id of this PipelineTemplateFullDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this PipelineTemplateFullDto.  # noqa: E501

        Name of the pipeline template. NotEmpty, MaximumLength(80).  # noqa: E501

        :return: The name of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PipelineTemplateFullDto.

        Name of the pipeline template. NotEmpty, MaximumLength(80).  # noqa: E501

        :param name: The name of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this PipelineTemplateFullDto.  # noqa: E501

        Description of the pipeline template. Nullable, MaximumLength(512).  # noqa: E501

        :return: The description of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PipelineTemplateFullDto.

        Description of the pipeline template. Nullable, MaximumLength(512).  # noqa: E501

        :param description: The description of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def template(self):
        """Gets the template of this PipelineTemplateFullDto.  # noqa: E501

        Template of the pipeline template. NotEmpty.  # noqa: E501

        :return: The template of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this PipelineTemplateFullDto.

        Template of the pipeline template. NotEmpty.  # noqa: E501

        :param template: The template of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._template = template

    @property
    def default_value(self):
        """Gets the default_value of this PipelineTemplateFullDto.  # noqa: E501

        Default values of the pipeline template. NotEmpty.  # noqa: E501

        :return: The default_value of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """Sets the default_value of this PipelineTemplateFullDto.

        Default values of the pipeline template. NotEmpty.  # noqa: E501

        :param default_value: The default_value of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._default_value = default_value

    @property
    def item_id(self):
        """Gets the item_id of this PipelineTemplateFullDto.  # noqa: E501

        ItemId value of the pipeline template. NotEmpty.  # noqa: E501

        :return: The item_id of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this PipelineTemplateFullDto.

        ItemId value of the pipeline template. NotEmpty.  # noqa: E501

        :param item_id: The item_id of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def parameters(self):
        """Gets the parameters of this PipelineTemplateFullDto.  # noqa: E501

        Definition of parameters used in the template.  # noqa: E501

        :return: The parameters of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this PipelineTemplateFullDto.

        Definition of parameters used in the template.  # noqa: E501

        :param parameters: The parameters of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._parameters = parameters

    @property
    def id_pipeline_type(self):
        """Gets the id_pipeline_type of this PipelineTemplateFullDto.  # noqa: E501


        :return: The id_pipeline_type of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: PipelineTypeEnum
        """
        return self._id_pipeline_type

    @id_pipeline_type.setter
    def id_pipeline_type(self, id_pipeline_type):
        """Sets the id_pipeline_type of this PipelineTemplateFullDto.


        :param id_pipeline_type: The id_pipeline_type of this PipelineTemplateFullDto.  # noqa: E501
        :type: PipelineTypeEnum
        """

        self._id_pipeline_type = id_pipeline_type

    @property
    def id_pipeline_template_platform(self):
        """Gets the id_pipeline_template_platform of this PipelineTemplateFullDto.  # noqa: E501


        :return: The id_pipeline_template_platform of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: PipelineTemplatePlatformEnum
        """
        return self._id_pipeline_template_platform

    @id_pipeline_template_platform.setter
    def id_pipeline_template_platform(self, id_pipeline_template_platform):
        """Sets the id_pipeline_template_platform of this PipelineTemplateFullDto.


        :param id_pipeline_template_platform: The id_pipeline_template_platform of this PipelineTemplateFullDto.  # noqa: E501
        :type: PipelineTemplatePlatformEnum
        """

        self._id_pipeline_template_platform = id_pipeline_template_platform

    @property
    def id_plugin_version(self):
        """Gets the id_plugin_version of this PipelineTemplateFullDto.  # noqa: E501

        Plugin version identifier  # noqa: E501

        :return: The id_plugin_version of this PipelineTemplateFullDto.  # noqa: E501
        :rtype: str
        """
        return self._id_plugin_version

    @id_plugin_version.setter
    def id_plugin_version(self, id_plugin_version):
        """Sets the id_plugin_version of this PipelineTemplateFullDto.

        Plugin version identifier  # noqa: E501

        :param id_plugin_version: The id_plugin_version of this PipelineTemplateFullDto.  # noqa: E501
        :type: str
        """

        self._id_plugin_version = id_plugin_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PipelineTemplateFullDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PipelineTemplateFullDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
