import multiprocessing.queues
from typing import Optional

class JsonFile:
    def __init__(self, path: str) -> None: ...
    @property
    def contents(self) -> Optional[dict]: ...
    def exists(self) -> bool: ...
    def load(self) -> bool: ...

class MultiprocessingCircularQueue(multiprocessing.queues.Queue):
    def __init__(self, *args, **kwargs) -> None: ...
    def put(self, obj) -> None: ...

def empty_queue(q) -> None: ...
