# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    Sidra API version: 1.13.0.dev5
    Contact: sidra@plainconcepts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Output(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pipeline_name': 'str',
        'pipeline_run_id': 'str'
    }

    attribute_map = {
        'pipeline_name': 'pipelineName',
        'pipeline_run_id': 'pipelineRunId'
    }

    def __init__(self, pipeline_name=None, pipeline_run_id=None):  # noqa: E501
        """Output - a model defined in Swagger"""  # noqa: E501
        self._pipeline_name = None
        self._pipeline_run_id = None
        self.discriminator = None
        if pipeline_name is not None:
            self.pipeline_name = pipeline_name
        if pipeline_run_id is not None:
            self.pipeline_run_id = pipeline_run_id

    @property
    def pipeline_name(self):
        """Gets the pipeline_name of this Output.  # noqa: E501

        Pipeline Name  # noqa: E501

        :return: The pipeline_name of this Output.  # noqa: E501
        :rtype: str
        """
        return self._pipeline_name

    @pipeline_name.setter
    def pipeline_name(self, pipeline_name):
        """Sets the pipeline_name of this Output.

        Pipeline Name  # noqa: E501

        :param pipeline_name: The pipeline_name of this Output.  # noqa: E501
        :type: str
        """

        self._pipeline_name = pipeline_name

    @property
    def pipeline_run_id(self):
        """Gets the pipeline_run_id of this Output.  # noqa: E501

        Pipeline run id  # noqa: E501

        :return: The pipeline_run_id of this Output.  # noqa: E501
        :rtype: str
        """
        return self._pipeline_run_id

    @pipeline_run_id.setter
    def pipeline_run_id(self, pipeline_run_id):
        """Sets the pipeline_run_id of this Output.

        Pipeline run id  # noqa: E501

        :param pipeline_run_id: The pipeline_run_id of this Output.  # noqa: E501
        :type: str
        """

        self._pipeline_run_id = pipeline_run_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Output, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Output):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
