# Constants
SCREEN_WIDTH = 1080
SCREEN_HEIGHT = 810
SCREEN_TITLE = "Platformer"
CHARACTER_SCALING = 3
TILE_SCALING = 3

# Movement speed of player, in pixels per frame
PLAYER_MOVEMENT_SPEED = 5
MOVE_SPEED = 2
GRAVITY = 1
PLAYER_JUMP_SPEED = 1
JUMP_SPEED = 10
RIGHT_FACING = 0
LEFT_FACING = 1

BULLET_SIZE = 2
BULLET_SPEED = 8
BULLET_RADIUS = 100
FORM_TIMER = 10

BOSS_STUN_TIME = 3
BOSS_PATH = [[530,530], [145,700], [915,700]]