
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-27T17:28:04-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "b972fdc9822ef53984ff6e147da90ddc0bfa8bcd",
 "version": "0.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
