# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kerfed/protos/api/v1/file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fkerfed/protos/api/v1/file.proto\x12\x14kerfed.protos.api.v1\x1a\x1cgoogle/api/annotations.proto\"R\n\x11\x46ileUploadRequest\x12\x1a\n\x08\x66ilename\x18\x01 \x01(\tR\x08\x66ilename\x12!\n\x0c\x63ontent_type\x18\x02 \x01(\tR\x0b\x63ontentType\"L\n\x12\x46ileUploadResponse\x12\x17\n\x07\x66ile_id\x18\x01 \x01(\tR\x06\x66ileId\x12\x1d\n\nupload_url\x18\x02 \x01(\tR\tuploadUrl\".\n\x13\x46ileDownloadRequest\x12\x17\n\x07\x66ile_id\x18\x01 \x01(\tR\x06\x66ileId\"R\n\x14\x46ileDownloadResponse\x12\x17\n\x07\x66ile_id\x18\x01 \x01(\tR\x06\x66ileId\x12!\n\x0c\x64ownload_url\x18\x02 \x01(\tR\x0b\x64ownloadUrl2\xf6\x01\n\x04\x46ile\x12n\n\x06Upload\x12\'.kerfed.protos.api.v1.FileUploadRequest\x1a(.kerfed.protos.api.v1.FileUploadResponse\"\x11\x82\xd3\xe4\x93\x02\x0b\"\t/v1/files\x12~\n\x08\x44ownload\x12).kerfed.protos.api.v1.FileDownloadRequest\x1a*.kerfed.protos.api.v1.FileDownloadResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/files/{file_id}B\xcd\x01\n\x18\x63om.kerfed.protos.api.v1B\tFileProtoP\x01Z3github.com/kerfed/protos/kerfed/protos/api/v1;apiv1\xa2\x02\x03KPA\xaa\x02\x14Kerfed.Protos.Api.V1\xca\x02\x14Kerfed\\Protos\\Api\\V1\xe2\x02 Kerfed\\Protos\\Api\\V1\\GPBMetadata\xea\x02\x17Kerfed::Protos::Api::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kerfed.protos.api.v1.file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.kerfed.protos.api.v1B\tFileProtoP\001Z3github.com/kerfed/protos/kerfed/protos/api/v1;apiv1\242\002\003KPA\252\002\024Kerfed.Protos.Api.V1\312\002\024Kerfed\\Protos\\Api\\V1\342\002 Kerfed\\Protos\\Api\\V1\\GPBMetadata\352\002\027Kerfed::Protos::Api::V1'
  _FILE.methods_by_name['Upload']._options = None
  _FILE.methods_by_name['Upload']._serialized_options = b'\202\323\344\223\002\013\"\t/v1/files'
  _FILE.methods_by_name['Download']._options = None
  _FILE.methods_by_name['Download']._serialized_options = b'\202\323\344\223\002\025\022\023/v1/files/{file_id}'
  _globals['_FILEUPLOADREQUEST']._serialized_start=87
  _globals['_FILEUPLOADREQUEST']._serialized_end=169
  _globals['_FILEUPLOADRESPONSE']._serialized_start=171
  _globals['_FILEUPLOADRESPONSE']._serialized_end=247
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=249
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=295
  _globals['_FILEDOWNLOADRESPONSE']._serialized_start=297
  _globals['_FILEDOWNLOADRESPONSE']._serialized_end=379
  _globals['_FILE']._serialized_start=382
  _globals['_FILE']._serialized_end=628
# @@protoc_insertion_point(module_scope)
