
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-24T13:21:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6df2792ab6a781cbb78133f4b35374d4ce95625",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
