
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-27T18:08:17+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "078d5b058d9b0c6a87b88a619cd5798d51bd8530",
 "version": "1.2.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
