__title__ = 'xmindruntestcase'
__description__ = 'xmindruntestcase基于Python实现，提供了一个高效测试用例设计的解决方案！可以实现xmind转csv，csv转xmind操作！'
__keywords__ = 'xmindruntestcase, testcase, test, testing, xmind, 思维导图, XMind思维导图',
__url__ = 'https://github.com/huc141/xmindTotestcase.git'
__author__ = 'yulong'
__author_email__ = '1349983371@qq.com'
__version__ = '2.0.0'
__license__ = 'MIT'
__cake__ = u'\u2728 \U0001f370 \u2728'
