# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: sidra@plainconcepts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.api.release_note_release_notes_api import ReleaseNoteReleaseNotesApi  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestReleaseNoteReleaseNotesApi(unittest.TestCase):
    """ReleaseNoteReleaseNotesApi unit test stubs"""

    def setUp(self):
        self.api = ReleaseNoteReleaseNotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_management_release_notes_get(self):
        """Test case for api_management_release_notes_get

        Gets a list of release notes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
