# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: sidra@plainconcepts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.common_model_suggest_request_dto import CommonModelSuggestRequestDTO  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestCommonModelSuggestRequestDTO(unittest.TestCase):
    """CommonModelSuggestRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonModelSuggestRequestDTO(self):
        """Test CommonModelSuggestRequestDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.common_model_suggest_request_dto.CommonModelSuggestRequestDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
