# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: sidra@plainconcepts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.api_model_serving_models_model_version_execution import APIModelServingModelsModelVersionExecution  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestAPIModelServingModelsModelVersionExecution(unittest.TestCase):
    """APIModelServingModelsModelVersionExecution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAPIModelServingModelsModelVersionExecution(self):
        """Test APIModelServingModelsModelVersionExecution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.api_model_serving_models_model_version_execution.APIModelServingModelsModelVersionExecution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
