
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-26T08:50:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "836fd2a8cf856b32f10d8bb9cdf61e4999775053",
 "version": "7.31.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
