from dash import Dash, html

app = Dash(__name__)

app.layout = html.Div([
    html.Button('+   Button', id='Small',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '7px 16px', 'gap': '8px', 'position': 'relative', 'width': '103px',
                       'height': '32px', 'background': '#003FE2', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('+   Button', id='Medium',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '119px',
                       'height': '48px', 'background': '#003FE2', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('+   Button', id='Large',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '16px 32px', 'gap': '12px', 'position': 'relative', 'width': '153px',
                       'height': '56px', 'background': '#003FE2', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '17px', 'line-height': '24px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('🔔️', id='Xss icon',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '10px', 'position': 'relative', 'width': '40px',
                       'height': '40px', 'background': '#003FE2', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('Button', id='Primary',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '95px',
                       'height': '48px', 'background': '#003FE2', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('Button', id='Secondary',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '95px',
                       'height': '48px', 'background': '#ffffff', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#003FE2', 'border': '1px solid #003FE2', 'margin-top': '10px'}),
    html.Button('Button', id='Tertiary',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '95px',
                       'height': '48px', 'background': '#66BFFF', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('Button', id='Transparent',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '95px',
                       'height': '48px', 'background': 'transparent', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#003FE2', 'border': 'none', 'margin-top': '10px'}),
    html.Button('Button', id='Warning',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '95px',
                       'height': '48px', 'background': '#E84C4E', 'border-radius': '1px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Button('Button', id='Floating',
                style={'background-color': '#003FE2', 'font-family': 'NOTO SANS', 'display': 'flex',
                       'flex-direction': 'row', 'justify-content': 'center', 'align-item': 'center',
                       'padding': '15px 24px', 'gap': '8px', 'position': 'relative', 'width': '95px',
                       'height': '48px', 'background': '#003FE2', 'border-radius': '91px',
                       'font-weight': '700', 'font-size': '14px', 'line-height': '18px', 'letter-spacing': '-0.5px',
                       'color': '#FFFFFF', 'border': 'none', 'margin-top': '10px'}),
    html.Div(id='container-button-timestamp')
])

if __name__ == '__main__':
    app.run_server(port=8090, debug=True)
