
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-23T21:24:55-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f8c7846b0c90c3f1855ce4fc817fb2d47b9912e",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
