TEST_FILTER_PROCESS_TIME = 0.03125
TEST_IFO_NAME = 'T1'
TEST_SUBSYS_NAME = 'TEST'
TEST_FILTER_NAME = 'FILTER'
TEST_FILTER_PREFIX = TEST_IFO_NAME+':'+TEST_SUBSYS_NAME+'-'+TEST_FILTER_NAME+'_'
TEST_FILTER_RANDOM_ENGAGE_BOUNDS = (0.1,1)
TEST_FILTER_RANDOM_DISENGAGE_BOUNDS = (0.1,1)
TEST_FILTER_RAMP_TEST_TIME = 5
TEST_RAMP_WAIT_RETURN_TOLERANCE = 0.125  # seconds

TEST_MULTIPLE_BUTTON_LISTS = [
        ['FM'+str(i) for i in range(1,11)],
        ['INPUT','FM1','FM2'],
        ['OUTPUT','OFFSET','FM6'],
]
