CACHE_SIZE = 256

NAMED_REGEX = r':[\w|\d]*'

MYSQL, POSTGRESQL, UNKNOW = 'MySQL', 'PostgreSQL', 'Unknow'

MYSQLCLIENT, PYMYSQL, MYSQL_CONNECTOR, PSYCOPG2, PG8000 = 'MySQLdb', 'pymysql', 'mysql.connector', 'psycopg2', 'pg8000'

DRIVERS = {MYSQLCLIENT: MYSQL, PYMYSQL: MYSQL, MYSQL_CONNECTOR: MYSQL, PSYCOPG2: POSTGRESQL, PG8000: POSTGRESQL}
