# Generated by Django 4.2.3 on 2023-07-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onoffmonitorserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='gpio_pin',
            new_name='gpio_input',
        ),
        migrations.AddField(
            model_name='device',
            name='gpio_led',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GPIO LED pin on monitor'),
        ),
    ]
