# Generated by Django 4.2.3 on 2023-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onoffmonitorserver', '0002_alter_device_gpio_pin_device_gpio_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='gpio_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'BOARD'), (1, 'BCM')], default=0, verbose_name='GPIO pin mode'),
        ),
        migrations.AlterField(
            model_name='device',
            name='gpio_input',
            field=models.PositiveSmallIntegerField(verbose_name='GPIO input pin on monitor'),
        ),
    ]
