
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-23T15:48:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c0f16d8782ae6cb366e26cb548c95386f86f991",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
