# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoAnalyticSetAnalyticCollectionCreated(Model):
    """Encapsulates the results of a successfully created analytic collection.

    :param name: The name of the AnalyticCollection
    :type name: str
    :param group_id: The group identifier of the AnalyticCollection
    :type group_id: str
    :param location: The full URL of the newly created AnalyticCollection
    :type location: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'group_id': {'key': 'groupId', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(AdiEmsWebApiV2DtoAnalyticSetAnalyticCollectionCreated, self).__init__(**kwargs)
        self.name = kwargs.get('name', None)
        self.group_id = kwargs.get('group_id', None)
        self.location = kwargs.get('location', None)
