
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-25T19:20:45+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "738bf3308ace6e8786612df0c98075b6a23bf6b9",
 "version": "1.2.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
