# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoAlertAddActivity(Model):
    """Input data type for adding to the history of an alert for some entity (e.g.
    an aircraft).

    :param trigger_date: The timestamp of the data that triggered the alert
     activity (for instance, if the alert activity
     was triggered by analysis of a flight, the flight date could be considered
     the trigger date)
    :type trigger_date: datetime
    :param is_active: Specifies whether the alert was/became Active or
     Inactive at the given trigger date
    :type is_active: bool
    :param sort_key: A sortable string which orders the alert activity in
     ascending real-world chronological order
    :type sort_key: str
    :param trigger_agent: Optional: caller-defined free-form string that
     identifies the agent which recorded the activity,
     such as a profile number.
    :type trigger_agent: str
    :param trigger_reference_type: Optional: caller-defined information which
     identifies what type of information
     is stored in TriggerReferenceValue
    :type trigger_reference_type: str
    :param trigger_reference_value: Optional: a record number or other value
     which is associated with this alert
     state change. For example, this may be the record number of a flight whose
     data was the cause of the state change (maybe through an APM alert
     trigger).
    :type trigger_reference_value: int
    """

    _attribute_map = {
        'trigger_date': {'key': 'triggerDate', 'type': 'iso-8601'},
        'is_active': {'key': 'isActive', 'type': 'bool'},
        'sort_key': {'key': 'sortKey', 'type': 'str'},
        'trigger_agent': {'key': 'triggerAgent', 'type': 'str'},
        'trigger_reference_type': {'key': 'triggerReferenceType', 'type': 'str'},
        'trigger_reference_value': {'key': 'triggerReferenceValue', 'type': 'int'},
    }

    def __init__(self, *, trigger_date=None, is_active: bool=None, sort_key: str=None, trigger_agent: str=None, trigger_reference_type: str=None, trigger_reference_value: int=None, **kwargs) -> None:
        super(AdiEmsWebApiV2DtoAlertAddActivity, self).__init__(**kwargs)
        self.trigger_date = trigger_date
        self.is_active = is_active
        self.sort_key = sort_key
        self.trigger_agent = trigger_agent
        self.trigger_reference_type = trigger_reference_type
        self.trigger_reference_value = trigger_reference_value
