# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2ModelAdminApiClient(Model):
    """Represents an API client application that consumes REST services hosted in
    the website.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. The unique integer identifier of the API client
    :type id: int
    :param client_id: Required. The unique, user friendly, client ID of the
     client, used when clients request tokens to access the API
    :type client_id: str
    :param description: A brief summary describing the API client and its
     purpose
    :type description: str
    :param redirect_uri: The redirect or callback URI for specific grant types
     (e.g. implicit).
    :type redirect_uri: str
    :param grant_type: Required. The grant type that may be used by the client
     to access the API. Possible values include: 'trusted', 'password',
     'implicit'
    :type grant_type: str or ~emsapi.models.enum
    :param enabled: Required. Indicates whether the API client is active and
     can currently consume the API
    :type enabled: bool
    :param created: Required. The date and time at which the API client record
     was created
    :type created: datetime
    :param updated: Required. The date and time at which the API client record
     was last updated
    :type updated: datetime
    """

    _validation = {
        'id': {'required': True},
        'client_id': {'required': True},
        'grant_type': {'required': True},
        'enabled': {'required': True},
        'created': {'required': True},
        'updated': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'int'},
        'client_id': {'key': 'clientId', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'redirect_uri': {'key': 'redirectUri', 'type': 'str'},
        'grant_type': {'key': 'grantType', 'type': 'str'},
        'enabled': {'key': 'enabled', 'type': 'bool'},
        'created': {'key': 'created', 'type': 'iso-8601'},
        'updated': {'key': 'updated', 'type': 'iso-8601'},
    }

    def __init__(self, **kwargs):
        super(AdiEmsWebApiV2ModelAdminApiClient, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.client_id = kwargs.get('client_id', None)
        self.description = kwargs.get('description', None)
        self.redirect_uri = kwargs.get('redirect_uri', None)
        self.grant_type = kwargs.get('grant_type', None)
        self.enabled = kwargs.get('enabled', None)
        self.created = kwargs.get('created', None)
        self.updated = kwargs.get('updated', None)
