# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SystemThreadingCancellationToken(Model):
    """SystemThreadingCancellationToken.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar is_cancellation_requested:
    :vartype is_cancellation_requested: bool
    :ivar can_be_canceled:
    :vartype can_be_canceled: bool
    :ivar wait_handle:
    :vartype wait_handle: ~emsapi.models.SystemThreadingWaitHandle
    """

    _validation = {
        'is_cancellation_requested': {'readonly': True},
        'can_be_canceled': {'readonly': True},
        'wait_handle': {'readonly': True},
    }

    _attribute_map = {
        'is_cancellation_requested': {'key': 'isCancellationRequested', 'type': 'bool'},
        'can_be_canceled': {'key': 'canBeCanceled', 'type': 'bool'},
        'wait_handle': {'key': 'waitHandle', 'type': 'SystemThreadingWaitHandle'},
    }

    def __init__(self, **kwargs):
        super(SystemThreadingCancellationToken, self).__init__(**kwargs)
        self.is_cancellation_requested = None
        self.can_be_canceled = None
        self.wait_handle = None
