import numpy as np
from .types import PostProcessParams, PreProcessParams

def dnn_pre_process(params: PreProcessParams) -> np.ndarray: ...
def ssd_post_process(params: PostProcessParams): ...
def ssd_flat_post_process(results: np.ndarray, image: np.ndarray, confidence_level: float): ...
def yolo_post_process(params: PostProcessParams): ...
