# Generated by Django 3.2.19 on 2023-07-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0045_version_4_5_5'),
        ('NEMO_stockroom', '0004_alter_consumablerequest_date_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumablerequest',
            name='withdraw',
            field=models.ForeignKey(blank=True, help_text='Withdrawal associated with this request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_date', to='NEMO.consumablewithdraw'),
        ),
    ]
