#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2304-16-g39c5cbc3"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2304
#define NETGEN_VERSION_TWEAK 16
#define NETGEN_VERSION_HASH "g39c5cbc3"
#endif // NETGEN_VERSION_HPP_INCLUDED
