# coding: utf-8

"""
    Sidra API

    Sidra API  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: sidra@plainconcepts.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraCoreApiPythonClient
from SidraCoreApiPythonClient.models.microsoft_azure_databricks_client_export_format import MicrosoftAzureDatabricksClientExportFormat  # noqa: E501
from SidraCoreApiPythonClient.rest import ApiException


class TestMicrosoftAzureDatabricksClientExportFormat(unittest.TestCase):
    """MicrosoftAzureDatabricksClientExportFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMicrosoftAzureDatabricksClientExportFormat(self):
        """Test MicrosoftAzureDatabricksClientExportFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraCoreApiPythonClient.models.microsoft_azure_databricks_client_export_format.MicrosoftAzureDatabricksClientExportFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
