
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-26T16:35:28+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "83f8860ebf2bee68110a2d3e79fafe07944bf3fc",
 "version": "1.2.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
