# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.6.5.dev3+gdf78d88.d20230719'
__version_tuple__ = version_tuple = (0, 6, 5, 'dev3', 'gdf78d88.d20230719')
