
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-25T12:26:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2cbdc173adf6b04b36403ab1c13c211b4613d14",
 "version": "4.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
