
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-30T07:26:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb13af76c86be6fa317223270450d7858c11f6da",
 "version": "1.17.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
