VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('25')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('38')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202307251038
version_date = '2023/07/25 10:38'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
