#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ----------------------------------------------------------------------------------------------------------------------
# Author: Lalith Kumar Shiyam Sundar
# Institution: Medical University of Vienna
# Research Group: Quantitative Imaging and Medical Physics (QIMP) Team
# Date: 13.02.2023
# Version: 2.0.0
#
# Description:
# This module contains the urls and filenames of the models and binaries that are required for the moosez.
#
# Usage:
# The variables in this module can be imported and used in other modules within the moosez to download the necessary
# binaries and models for the moosez.
#
# ----------------------------------------------------------------------------------------------------------------------
import torch
import logging
from moosez import constants

# This list contains the unique identifiers for all available pre-trained models.
# To make your model available, add its unique identifier to this list.
# The model name or the unique identifier has a specific syntax:
# 'clin' or 'preclin' (indicating Clinical or Preclinical),
# modality tag (like 'ct', 'pt', 'mr'), and then the tissue of interest.

AVAILABLE_MODELS = ["clin_ct_lungs_v2",
                    "clin_ct_organs_v2",
                    "clin_pt_fdg_tumor_v2",
                    "clin_ct_body_v2",
                    "preclin_mr_all_v2",
                    "clin_ct_organs_v1",
                    "clin_ct_bones_v1",
                    "clin_ct_fat_muscles_v1"]

# This dictionary holds the pre-trained models available in MooseZ library.
# Each key is a unique model identifier following a specific syntax mentioned above
# It should have the same name mentioned in AVAILABLE_MODELS list.
# Each value is a dictionary containing the following keys:
#    - url: The URL where the model files can be downloaded.
#    - filename: The filename of the model's zip file.
#    - directory: The directory where the model files will be extracted.
#    - trainer: The type of trainer used to train the model.
#    - voxel_spacing: The voxel spacing used in the model in the form [x, y, z], this is basically the median voxel
#    spacing generated by nnunetv2, and you can find this in the plans.json file of the model.
#    - multilabel_prefix: A prefix to distinguish between different types of labels in multi-label models.
#
# To include your own model, add a new entry to this dictionary following the above format.

MODELS = {
    "clin_ct_lungs_v2": {
        "nnunet_version": "v2",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/clin_ct_lungs_24062023.zip",
        "filename": "Dataset333_HMS3dlungs.zip",
        "directory": "Dataset333_HMS3dlungs",
        "trainer": "nnUNetTrainer_2000epochs_NoMirroring",
        "voxel_spacing": [1.5, 1.5, 1.5],
        "multilabel_prefix": "CT_Lungs_",
        "model_type": None,
        "fold": None,
    },
    "clin_ct_organs_v2": {
        "nnunet_version": "v2",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/MOOSEv2_bspline_organs23062023.zip",
        "filename": "Dataset123_Organs.zip",
        "directory": "Dataset123_Organs",
        "trainer": "nnUNetTrainer_2000epochs_NoMirroring",
        "voxel_spacing": [1.5, 1.5, 1.5],
        "multilabel_prefix": "CT_Organs_",
        "model_type": None,
        "fold": None,
    },
    "clin_pt_fdg_tumor_v2": {
        "nnunet_version": "v2",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/Dataset789_Tumors.zip",
        "filename": "Dataset789_Tumors.zip",
        "directory": "Dataset789_Tumors",
        "trainer": "nnUNetTrainerDA5",
        "voxel_spacing": [1.5, 1.5, 1.5],
        "multilabel_prefix": "PT_FDG_Tumor_",
        "model_type": None,
        "fold": None,
    },
    "preclin_mr_all_v2": {
        "nnunet_version": "v2",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/preclin_mr_14062023.zip",
        "filename": "Dataset234_Preclin.zip",
        "directory": "Dataset234_Preclin",
        "trainer": "nnUNetTrainerNoMirroring",
        "voxel_spacing": [0.15, 0.15, 0.15],
        "multilabel_prefix": "Preclin_MR_all_",
        "model_type": None,
        "fold": None,
    },
    "clin_ct_body_v2": {
        "nnunet_version": "v2",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/Dataset696_BodyContour.zip",
        "filename": "Dataset696_BodyContour.zip",
        "directory": "Dataset696_BodyContour",
        "trainer": "nnUNetTrainer",
        "voxel_spacing": [1.5, 1.5, 1.5],
        "multilabel_prefix": "CT_Body_",
        "model_type": None,
        "fold": None,
    },
    "clin_ct_organs_v1": {
        "nnunet_version": "v1",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/Task123_StOrgans40.zip",
        "filename": "Task123_StOrgans40.zip",
        "directory": "Task123_StOrgans40",
        "trainer": None,
        "voxel_spacing": [0.9765625, 0.9765625, 2.3440001],
        "multilabel_prefix": "CT_Organs_V1_",
        "model_type": "3d_fullres",
        "fold": "all",
    },
    "clin_ct_bones_v1": {
        "nnunet_version": "v1",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/Task517_Bones40.zip",
        "filename": "Task517_Bones40.zip",
        "directory": "Task517_Bones40",
        "trainer": None,
        "voxel_spacing": [0.9765625, 0.9765625, 2.3440001],
        "multilabel_prefix": "CT_Bones_V1_",
        "model_type": "3d_fullres",
        "fold": "all",
    },
    "clin_ct_fat_muscles_v1": {
        "nnunet_version": "v1",
        "url": "https://moose-files.s3.eu-de.cloud-object-storage.appdomain.cloud/Task517_Bones40.zip",
        "filename": "Task427_FM40.zip",
        "directory": "Task427_FM40",
        "trainer": None,
        "voxel_spacing": [0.9765625, 0.9765625, 2.3440001],
        "multilabel_prefix": "CT_Fat_Muscles_V1_",
        "model_type": "3d_fullres",
        "fold": "all",
    },

}


# This function returns a dictionary indicating the expected modality for a given model_name, the imaging technique,
# the type of tissue to be segmented. The model_name should be the same as the unique identifier mentioned in the
# MODELS dictionary above and the AVAILABLE_MODELS list.
# If the model_name is not found, it logs an error message and returns an error message.
#
# If you add your own model, update this function to return the expected modality dictionary for your model.

def expected_modality(model_name: str) -> dict:
    """
    Display expected modality for the model.
    :param model_name: The name of the model.
    :return: The expected modality for the model.
    """
    models = {
        "clin_ct_lungs_v2": {"Imaging": "Clinical", "Modality": "CT", "Tissue of interest": "Lungs",
                          "nnUNet version": "v2"},
        "clin_ct_organs_v2": {"Imaging": "Clinical", "Modality": "CT", "Tissue of interest": "Organs",
                           "nnUNet version": "v2"},
        "clin_pt_fdg_tumor_v2": {"Imaging": "Clinical", "Modality": "PET", "Tissue of interest": "Tumor",
                              "nnUNet version": "v2"},
        "clin_ct_body_v2": {"Imaging": "Clinical", "Modality": "CT", "Tissue of interest": "Body",
                         "nnUNet version": "v2"},
        "preclin_mr_all_v2": {"Imaging": "Pre-clinical", "Modality": "MR", "Tissue of interest": "All regions",
                           "nnUNet version": "v2"},
        "clin_ct_organs_v1": {"Imaging": "Clinical", "Modality": "CT", "Tissue of interest": "Organs",
                              "nnUNet version": "v1"},
        "clin_ct_bones_v1": {"Imaging": "Clinical", "Modality": "CT", "Tissue of interest": "Bones",
                             "nnUNet version": "v1"},
        "clin_ct_fat_muscles_v1": {"Imaging": "Clinical", "Modality": "CT", "Tissue of interest": "Fat and Muscles",
                                   "nnUNet version": "v1"},
    }

    if model_name in models:
        model = models[model_name]
        model["Model name"] = model_name
        return model

    logging.error(" Requested model is not available. Please check the model name.")
    return {"Error": "Requested model is not available. Please check the model name."}


# This function maps the model name to the task number. This is the number that comes after Dataset in DatasetXXXX,
# after nnunetv2 training. If your model folder is Dataset123, then the task number is 123.
# It checks for known model names and returns the associated task number, this is ABSOLUTELY NEEDED for the moosez to
# work. If the provided model name doesn't match any known model, it raises an exception.

# When adding your own model, update this function to return the task number associated with your model.

def map_model_name_to_task_number(model_name: str):
    """
    Maps the model name to the task number.
    :param model_name: The name of the model.
    :return: The task number.
    """
    if model_name == "clin_ct_lungs_v2":
        return 333
    elif model_name == "clin_ct_organs_v2":
        return 123
    elif model_name == "clin_pt_fdg_tumor_v2":
        return 789
    elif model_name == "preclin_mr_all_v2":
        return 234
    elif model_name == "clin_ct_body_v2":
        return 696
    elif model_name == "clin_ct_organs_v1":
        return 123
    elif model_name == "clin_ct_bones_v1":
        return 517
    elif model_name == "clin_ct_fat_muscles_v1":
        return 427
    else:
        raise Exception(f"Error: The model name '{model_name}' is not valid.")


def check_cuda() -> str:
    """
    This function checks if CUDA is available on the device and prints the device name and number of CUDA devices
    available on the device.

    Returns:
        str: The device to run predictions on, either "cpu" or "cuda".
    """
    if not torch.cuda.is_available():
        print(
            f"{constants.ANSI_ORANGE}CUDA not available on this device. Predictions will be run on CPU.{constants.ANSI_RESET}")
        return "cpu"
    else:
        device_count = torch.cuda.device_count()
        print(
            f"{constants.ANSI_GREEN} CUDA is available on this device with {device_count} GPU(s). Predictions will be run on GPU.{constants.ANSI_RESET}")
        return "cuda"
