
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-25T16:10:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "71e572843e857bf6531e9f8ed62e1625a1efd69e",
 "version": "1.0a.post5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
