# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kerfed/protos/api/v1/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gnostic.openapi.v3 import annotations_pb2 as gnostic_dot_openapi_dot_v3_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ekerfed/protos/api/v1/api.proto\x12\x14kerfed.protos.api.v1\x1a$gnostic/openapi/v3/annotations.protoB\x98\x03\n\x18\x63om.kerfed.protos.api.v1B\x08\x41piProtoP\x01Z3github.com/kerfed/protos/kerfed/protos/api/v1;apiv1\xa2\x02\x03KPA\xaa\x02\x14Kerfed.Protos.Api.V1\xca\x02\x14Kerfed\\Protos\\Api\\V1\xe2\x02 Kerfed\\Protos\\Api\\V1\\GPBMetadata\xea\x02\x17Kerfed::Protos::Api::V1\xbaG\xc8\x01\x12\x7f\n\nKerfed API\x12(Kerfed API for Intelligent Manufacturing\"1\n\x06Kerfed\x12\x13https://kerfed.com/\x1a\x12\x63ontact@kerfed.com*\r\n\x0bProprietary2\x05\x30.0.0*E:C\n\x1c\n\tBasicAuth\x12\x0f\n\r\n\x04http*\x05\x62\x61sic\n#\n\nBearerAuth\x12\x15\n\x13\n\x04http*\x06\x62\x65\x61rer2\x03JWTb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kerfed.protos.api.v1.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.kerfed.protos.api.v1B\010ApiProtoP\001Z3github.com/kerfed/protos/kerfed/protos/api/v1;apiv1\242\002\003KPA\252\002\024Kerfed.Protos.Api.V1\312\002\024Kerfed\\Protos\\Api\\V1\342\002 Kerfed\\Protos\\Api\\V1\\GPBMetadata\352\002\027Kerfed::Protos::Api::V1\272G\310\001\022\177\n\nKerfed API\022(Kerfed API for Intelligent Manufacturing\"1\n\006Kerfed\022\023https://kerfed.com/\032\022contact@kerfed.com*\r\n\013Proprietary2\0050.0.0*E:C\n\034\n\tBasicAuth\022\017\n\r\n\004http*\005basic\n#\n\nBearerAuth\022\025\n\023\n\004http*\006bearer2\003JWT'
# @@protoc_insertion_point(module_scope)
