# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kerfed.protos.api.v1 import assembly_pb2 as kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2


class AssemblyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/kerfed.protos.api.v1.Assembly/Create',
                request_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyCreateRequest.SerializeToString,
                response_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyCreateResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/kerfed.protos.api.v1.Assembly/Read',
                request_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyReadRequest.SerializeToString,
                response_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyReadResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/kerfed.protos.api.v1.Assembly/List',
                request_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyListRequest.SerializeToString,
                response_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyListResponse.FromString,
                )


class AssemblyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Create an assembly (typically from an uploaded file).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Read the content of a single assembly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List the assemblies that are currently available.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssemblyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyCreateRequest.FromString,
                    response_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyCreateResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyReadRequest.FromString,
                    response_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyReadResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyListRequest.FromString,
                    response_serializer=kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kerfed.protos.api.v1.Assembly', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Assembly(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kerfed.protos.api.v1.Assembly/Create',
            kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyCreateRequest.SerializeToString,
            kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kerfed.protos.api.v1.Assembly/Read',
            kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyReadRequest.SerializeToString,
            kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kerfed.protos.api.v1.Assembly/List',
            kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyListRequest.SerializeToString,
            kerfed_dot_protos_dot_api_dot_v1_dot_assembly__pb2.AssemblyListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
