
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-25T08:35:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "61bf0ec9a230251d57817abaa4134cd7f83f3e32",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
