
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-28T02:58:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a14c73530a9e7812a21b5bf73ba6a7dfeccc82f",
 "version": "0.0.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
