
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-07-25T16:55:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ecd5e849f04651942bc04bf1c12866aaad1a4f6",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
