VERSION_YEAR = 2023
VERSION_MONTH = int('07')
VERSION_DAY = int('25')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 1
MINOR_VERSION = 4
PATCH_VERSION = 202307251849
version_date = '2023/07/25 18:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
