
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-07T10:41:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cef0c2a076705c02727ac8a26108aaa6fa771f2a",
 "version": "23.06.00a+32.gcef0c2a"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
