# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev142+gfc48aa5.d20230725'
__version_tuple__ = version_tuple = (0, 1, 'dev142', 'gfc48aa5.d20230725')
