# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ldas',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/ldas',
                'lib_path': 'ldas'},
  'syms': { 'ldas.core': {'ldas.core.foo': ('core.html#foo', 'ldas/core.py')},
            'ldas.iiif': { 'ldas.iiif.Rectangle': ('iiif.html#rectangle', 'ldas/iiif.py'),
                           'ldas.iiif.Rectangle.compute_minimum_area_rectangle': ( 'iiif.html#rectangle.compute_minimum_area_rectangle',
                                                                                   'ldas/iiif.py'),
                           'ldas.iiif.Rectangle.convert': ('iiif.html#rectangle.convert', 'ldas/iiif.py'),
                           'ldas.iiif.Rectangle.convert_from_svg_str': ('iiif.html#rectangle.convert_from_svg_str', 'ldas/iiif.py'),
                           'ldas.iiif.Rectangle.create_svg_with_rectangle': ( 'iiif.html#rectangle.create_svg_with_rectangle',
                                                                              'ldas/iiif.py'),
                           'ldas.iiif.Rectangle.extract_points_from_svg': ('iiif.html#rectangle.extract_points_from_svg', 'ldas/iiif.py'),
                           'ldas.iiif.Rectangle.plot_bounding_box': ('iiif.html#rectangle.plot_bounding_box', 'ldas/iiif.py')}}}
